import type { Place } from "./types";

export const mockPlaces: Place[] = [
  {
    id: "plc-1",
    name: "Koerner Library Quiet Nook",
    building: "Irving K. Barber Learning Centre",
    floor: "3",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Soft chairs tucked behind the stacks with low foot traffic.",
    tags: ["quiet", "armchair", "library"],
    hours: "8am - 11pm",
    noise_level: "low",
    busy_level: "low",
    lighting: "soft",
    temperature: "cool",
    wifi: "strong",
    seating_type: "armchair",
    capacity: 6,
    photo_url:
      "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Library nook with soft chairs and warm lighting.",
    heart_count: 24,
    comment_count: 3,
    comments: [
      {
        id: "c-1",
        text: "Super quiet in the mornings.",
        created_at: "2024-08-12T09:10:00Z",
        photo_urls: [
          "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=600&q=80",
        ],
        heart_count: 4,
        replies: [
          {
            id: "c-1-r1",
            text: "Agree, mornings are perfect.",
            created_at: "2024-08-12T11:05:00Z",
          },
        ],
      },
      {
        id: "c-2",
        text: "Bring a sweater, the air is chilly.",
        created_at: "2024-08-12T10:02:00Z",
      },
      {
        id: "c-3",
        text: "Outlets are under the seats.",
        created_at: "2024-08-13T08:20:00Z",
      },
    ],
    lat: 49.26741,
    lng: -123.25206,
    last_verified_at: "2024-08-12",
  },
  {
    id: "plc-11",
    name: "IKB West Stair Loungers",
    building: "Irving K. Barber Learning Centre",
    floor: "2",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Low-traffic stair landing with cushioned benches.",
    tags: ["quiet", "bench", "library"],
    hours: "8am - 11pm",
    noise_level: "low",
    busy_level: "low",
    lighting: "warm",
    temperature: "cool",
    wifi: "strong",
    seating_type: "bench",
    capacity: 4,
    photo_url:
      "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Bench seating near a quiet stair landing.",
    heart_count: 7,
    comment_count: 1,
    comments: [
      {
        id: "c-6",
        text: "Hidden spot, almost empty.",
        created_at: "2024-08-13T09:30:00Z",
      },
    ],
    lat: 49.26762,
    lng: -123.25234,
    last_verified_at: "2024-08-13",
  },
  {
    id: "plc-12",
    name: "IKB Upper Reading Pods",
    building: "Irving K. Barber Learning Centre",
    floor: "4",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Pod chairs with built-in lamps and plenty of outlets.",
    tags: ["pod", "quiet", "library"],
    hours: "8am - 11pm",
    noise_level: "low",
    busy_level: "low",
    lighting: "dim",
    temperature: "cool",
    wifi: "strong",
    seating_type: "pod chair",
    capacity: 6,
    photo_url:
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Reading pods in a quiet library corner.",
    heart_count: 19,
    comment_count: 2,
    comments: [
      {
        id: "c-7",
        text: "Pods feel private and quiet.",
        created_at: "2024-08-15T10:18:00Z",
      },
      {
        id: "c-8",
        text: "Bring a blanket, chairs are cold.",
        created_at: "2024-08-15T12:40:00Z",
      },
    ],
    lat: 49.2679,
    lng: -123.2522,
    last_verified_at: "2024-08-15",
  },
  {
    id: "plc-2",
    name: "AMS Nest Lounge Pods",
    building: "AMS Student Nest",
    floor: "2",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Semi-enclosed pods near the windows, good for short rests.",
    tags: ["sofa", "window", "social"],
    hours: "7am - 12am",
    noise_level: "medium",
    busy_level: "high",
    lighting: "bright",
    temperature: "neutral",
    wifi: "strong",
    seating_type: "sofa",
    capacity: 10,
    photo_url:
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Lounge pods with soft seating near windows.",
    heart_count: 41,
    comment_count: 2,
    comments: [
      {
        id: "c-4",
        text: "Midday can be noisy, evenings are better.",
        created_at: "2024-08-05T14:34:00Z",
      },
      {
        id: "c-5",
        text: "Great for quick 20-min naps.",
        created_at: "2024-08-06T12:08:00Z",
      },
    ],
    lat: 49.26607,
    lng: -123.24972,
    last_verified_at: "2024-08-05",
  },
  {
    id: "plc-13",
    name: "Nest Third Floor Window Seats",
    building: "AMS Student Nest",
    floor: "3",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Soft window seats with a view over the plaza.",
    tags: ["window", "soft", "social"],
    hours: "7am - 12am",
    noise_level: "medium",
    busy_level: "medium",
    lighting: "bright",
    temperature: "neutral",
    wifi: "strong",
    seating_type: "window seat",
    capacity: 5,
    photo_url:
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Window seats with soft cushions.",
    heart_count: 28,
    comment_count: 1,
    comments: [
      {
        id: "c-9",
        text: "Nice breeze if windows are cracked.",
        created_at: "2024-08-07T15:03:00Z",
      },
    ],
    lat: 49.26618,
    lng: -123.2496,
    last_verified_at: "2024-08-07",
  },
  {
    id: "plc-14",
    name: "Nest Lower Atrium Sofas",
    building: "AMS Student Nest",
    floor: "1",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Clustered sofas near the atrium greenery.",
    tags: ["sofa", "social", "atrium"],
    hours: "7am - 12am",
    noise_level: "medium",
    busy_level: "high",
    lighting: "bright",
    temperature: "warm",
    wifi: "strong",
    seating_type: "sofa",
    capacity: 12,
    photo_url:
      "https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Sofa seating around an atrium.",
    heart_count: 33,
    comment_count: 2,
    comments: [
      {
        id: "c-10",
        text: "Great when it's quiet between events.",
        created_at: "2024-08-06T11:55:00Z",
        photo_urls: [
          "https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=600&q=80",
          "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=600&q=80",
        ],
        heart_count: 2,
        replies: [],
      },
      {
        id: "c-11",
        text: "Lots of outlets along the wall.",
        created_at: "2024-08-06T13:15:00Z",
      },
    ],
    lat: 49.26598,
    lng: -123.2499,
    last_verified_at: "2024-08-06",
  },
  {
    id: "plc-3",
    name: "Woodward Courtyard Bench",
    building: "Woodward IRC",
    floor: "1",
    outlet: false,
    is_public: true,
    approved: true,
    description: "Shaded bench with greenery and quiet airflow.",
    tags: ["outdoor", "bench", "shade"],
    hours: "6am - 10pm",
    noise_level: "low",
    busy_level: "low",
    lighting: "natural",
    temperature: "cool",
    wifi: "weak",
    seating_type: "bench",
    capacity: 4,
    photo_url:
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Shaded bench with greenery in a courtyard.",
    heart_count: 12,
    comment_count: 1,
    comments: [
      {
        id: "c-12",
        text: "Watch out for rain on windy days.",
        created_at: "2024-07-29T16:12:00Z",
      },
    ],
    lat: 49.26485,
    lng: -123.24692,
    last_verified_at: "2024-07-29",
  },
  {
    id: "plc-out-1",
    name: "Main Mall Lawn Patch",
    building: "Outdoor",
    floor: "N/A",
    outlet: false,
    is_public: true,
    approved: true,
    is_outdoor: true,
    description: "Grassy patch with trees for shade, bring a blanket.",
    tags: ["outdoor", "grass", "shade"],
    hours: "Always open",
    noise_level: "medium",
    busy_level: "medium",
    lighting: "natural",
    temperature: "warm",
    wifi: "weak",
    seating_type: "grass",
    capacity: 8,
    photo_url:
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Grassy outdoor area with trees.",
    heart_count: 17,
    comment_count: 1,
    comments: [
      {
        id: "c-out-1",
        text: "Great on sunny days, can be windy.",
        created_at: "2024-08-18T13:20:00Z",
      },
    ],
    lat: 49.26365,
    lng: -123.25295,
    last_verified_at: "2024-08-18",
  },
  {
    id: "plc-4",
    name: "Buchanan Tower Study Alcove",
    building: "Buchanan Tower",
    floor: "6",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Carpeted alcove with soft lighting and single seats.",
    tags: ["quiet", "study", "carpet"],
    hours: "7am - 9pm",
    noise_level: "low",
    busy_level: "low",
    lighting: "soft",
    temperature: "cool",
    wifi: "strong",
    seating_type: "single seat",
    capacity: 5,
    photo_url:
      "https://images.unsplash.com/photo-1486304873000-235643847519?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Quiet study alcove with soft lighting.",
    heart_count: 18,
    comment_count: 2,
    comments: [
      {
        id: "c-13",
        text: "Bring earplugs after 4pm.",
        created_at: "2024-08-09T17:40:00Z",
      },
      {
        id: "c-14",
        text: "Coziest chairs on the floor.",
        created_at: "2024-08-10T09:05:00Z",
      },
    ],
    lat: 49.26889,
    lng: -123.2553,
    last_verified_at: "2024-08-09",
  },
  {
    id: "plc-15",
    name: "Buchanan Tower Sky Bridge Chairs",
    building: "Buchanan Tower",
    floor: "7",
    outlet: false,
    is_public: true,
    approved: true,
    description: "Small lounge chairs near the sky bridge corridor.",
    tags: ["quiet", "chairs"],
    hours: "7am - 9pm",
    noise_level: "low",
    busy_level: "low",
    lighting: "soft",
    temperature: "cool",
    wifi: "medium",
    seating_type: "lounge chair",
    capacity: 3,
    photo_url:
      "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Quiet corridor with lounge chairs.",
    heart_count: 8,
    comment_count: 0,
    comments: [],
    lat: 49.26902,
    lng: -123.25552,
    last_verified_at: "2024-08-12",
  },
  {
    id: "plc-5",
    name: "Sauder Atrium Bench",
    building: "Sauder School of Business",
    floor: "1",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Warm sunlight mid-day; bring a hoodie.",
    tags: ["atrium", "sunlight"],
    hours: "8am - 9pm",
    noise_level: "medium",
    busy_level: "medium",
    lighting: "bright",
    temperature: "neutral",
    wifi: "strong",
    seating_type: "bench",
    capacity: 8,
    photo_url:
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Atrium seating with sunlight.",
    heart_count: 9,
    comment_count: 0,
    comments: [],
    lat: 49.26556,
    lng: -123.25343,
    last_verified_at: "2024-08-01",
  },
  {
    id: "plc-6",
    name: "LIFE Building Atrium Steps",
    building: "LIFE Building",
    floor: "1",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Wide wooden steps with soft lighting, quieter in mornings.",
    tags: ["atrium", "steps", "warm"],
    hours: "7am - 9pm",
    noise_level: "low",
    busy_level: "low",
    lighting: "warm",
    temperature: "neutral",
    wifi: "strong",
    seating_type: "steps",
    capacity: 12,
    photo_url:
      "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Indoor steps with warm lighting.",
    heart_count: 27,
    comment_count: 2,
    comments: [
      {
        id: "c-15",
        text: "Great between classes when it's quiet.",
        created_at: "2024-08-14T11:22:00Z",
      },
      {
        id: "c-16",
        text: "Seats get cold in winter.",
        created_at: "2024-08-14T13:40:00Z",
      },
    ],
    lat: 49.26163,
    lng: -123.24894,
    last_verified_at: "2024-08-14",
  },
  {
    id: "plc-out-2",
    name: "Rose Garden Bench",
    building: "Outdoor",
    floor: "N/A",
    outlet: false,
    is_public: true,
    approved: true,
    is_outdoor: true,
    description: "Quiet bench near the roses, best in late afternoon.",
    tags: ["outdoor", "bench", "quiet"],
    hours: "6am - 9pm",
    noise_level: "low",
    busy_level: "low",
    lighting: "natural",
    temperature: "cool",
    wifi: "weak",
    seating_type: "bench",
    capacity: 3,
    photo_url:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Outdoor bench by a garden.",
    heart_count: 21,
    comment_count: 1,
    comments: [
      {
        id: "c-out-2",
        text: "Smells amazing when roses bloom.",
        created_at: "2024-08-17T18:05:00Z",
      },
    ],
    lat: 49.26178,
    lng: -123.25385,
    last_verified_at: "2024-08-17",
  },
  {
    id: "plc-7",
    name: "CIRS Lounge Hammock Chair",
    building: "CIRS",
    floor: "2",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Eco-lounge with soft seating and lots of daylight.",
    tags: ["sofa", "daylight", "quiet"],
    hours: "8am - 8pm",
    noise_level: "low",
    busy_level: "medium",
    lighting: "bright",
    temperature: "neutral",
    wifi: "strong",
    seating_type: "lounge chair",
    capacity: 6,
    photo_url:
      "https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Lounge seating with daylight.",
    heart_count: 22,
    comment_count: 1,
    comments: [
      {
        id: "c-17",
        text: "Sunlight is perfect mid-afternoon.",
        created_at: "2024-08-10T15:10:00Z",
      },
    ],
    lat: 49.26202,
    lng: -123.25034,
    last_verified_at: "2024-08-10",
  },
  {
    id: "plc-16",
    name: "CIRS Quiet Corner Booths",
    building: "CIRS",
    floor: "1",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Booth seating tucked behind indoor plants.",
    tags: ["booth", "quiet", "plants"],
    hours: "8am - 8pm",
    noise_level: "low",
    busy_level: "low",
    lighting: "soft",
    temperature: "neutral",
    wifi: "strong",
    seating_type: "booth",
    capacity: 6,
    photo_url:
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Booth seating with greenery.",
    heart_count: 13,
    comment_count: 1,
    comments: [
      {
        id: "c-18",
        text: "Plants make it feel cozy.",
        created_at: "2024-08-11T10:10:00Z",
      },
    ],
    lat: 49.26212,
    lng: -123.25048,
    last_verified_at: "2024-08-11",
  },
  {
    id: "plc-8",
    name: "IKB Garden Terrace",
    building: "Irving K. Barber Learning Centre",
    floor: "4",
    outlet: false,
    is_public: true,
    approved: true,
    description: "Outdoor terrace with planters and breezy shade.",
    tags: ["outdoor", "terrace", "shade"],
    hours: "8am - 10pm",
    noise_level: "low",
    busy_level: "low",
    lighting: "natural",
    temperature: "cool",
    wifi: "weak",
    seating_type: "bench",
    capacity: 10,
    photo_url:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Outdoor terrace with planters.",
    heart_count: 14,
    comment_count: 1,
    comments: [
      {
        id: "c-19",
        text: "Best at sunset, bring a jacket.",
        created_at: "2024-08-08T19:30:00Z",
      },
    ],
    lat: 49.26782,
    lng: -123.25278,
    last_verified_at: "2024-08-08",
  },
  {
    id: "plc-9",
    name: "Chemistry Reading Corner",
    building: "Chemistry",
    floor: "2",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Carrel corner near tall windows, low foot traffic.",
    tags: ["quiet", "carrel", "window"],
    hours: "7am - 9pm",
    noise_level: "low",
    busy_level: "low",
    lighting: "soft",
    temperature: "neutral",
    wifi: "strong",
    seating_type: "carrel",
    capacity: 4,
    photo_url:
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Reading corner with window light.",
    heart_count: 11,
    comment_count: 0,
    comments: [],
    lat: 49.26274,
    lng: -123.2481,
    last_verified_at: "2024-08-02",
  },
  {
    id: "plc-17",
    name: "Chemistry North Lounge Bench",
    building: "Chemistry",
    floor: "1",
    outlet: false,
    is_public: true,
    approved: true,
    description: "Bench seating near the north hallway windows.",
    tags: ["bench", "window", "quiet"],
    hours: "7am - 9pm",
    noise_level: "low",
    busy_level: "low",
    lighting: "bright",
    temperature: "neutral",
    wifi: "medium",
    seating_type: "bench",
    capacity: 5,
    photo_url:
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Bench seating near windows.",
    heart_count: 6,
    comment_count: 0,
    comments: [],
    lat: 49.26258,
    lng: -123.24792,
    last_verified_at: "2024-08-13",
  },
  {
    id: "plc-10",
    name: "Totem Commons Booths",
    building: "Totem Park Commons",
    floor: "1",
    outlet: true,
    is_public: true,
    approved: true,
    description: "Booth seating with soft music and steady traffic.",
    tags: ["booth", "social", "indoors"],
    hours: "7am - 10pm",
    noise_level: "medium",
    busy_level: "high",
    lighting: "warm",
    temperature: "warm",
    wifi: "strong",
    seating_type: "booth",
    capacity: 8,
    photo_url:
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Indoor booth seating.",
    heart_count: 16,
    comment_count: 2,
    comments: [
      {
        id: "c-20",
        text: "Bring headphones, some chatter.",
        created_at: "2024-08-11T12:45:00Z",
      },
      {
        id: "c-21",
        text: "Best after lunch rush.",
        created_at: "2024-08-11T14:05:00Z",
      },
    ],
    lat: 49.26407,
    lng: -123.25467,
    last_verified_at: "2024-08-11",
  },
  {
    id: "plc-out-3",
    name: "Totem Park Courtyard Steps",
    building: "Outdoor",
    floor: "N/A",
    outlet: false,
    is_public: true,
    approved: true,
    is_outdoor: true,
    description: "Stone steps in the courtyard with a lot of sun.",
    tags: ["outdoor", "steps", "sunlight"],
    hours: "7am - 8pm",
    noise_level: "medium",
    busy_level: "medium",
    lighting: "natural",
    temperature: "warm",
    wifi: "weak",
    seating_type: "steps",
    capacity: 6,
    photo_url:
      "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=600&q=80",
    photo_alt: "Outdoor steps in a courtyard.",
    heart_count: 12,
    comment_count: 0,
    comments: [],
    lat: 49.2639,
    lng: -123.25512,
    last_verified_at: "2024-08-16",
  },
];
